[project]
name = "proxhy"
version = "2025.12.08"
description = "A Hypixel proxy with various different features"
license = "MIT"
authors = [
    {name = "Kavi Bidlack"},
    {name = "Manu Jhawar"}
]
requires-python = ">=3.14"
dependencies = [
    "hypixel.py>=0.4",
    "cryptography>=45.0",
    "keyring>=25.6",
    "pyjwt>=2.10",
    "platformdirs>=4.3",
    "numpy>=2.3.3",
    "uvloop>=0.22.1",
]

[project.scripts]
proxhy = "proxhy.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["proxhy", "core", "plugins", "auth", "protocol"]

[tool.setuptools.package-data]
"proxhy" = ["assets/*"]
