[project]
name = "proxhy"
version = "2025.12.17"
description = "A Hypixel proxy with various different features"
license = "MIT"
authors = [
    {name = "Kavi Bidlack"},
    {name = "Manu Jhawar"}
]
requires-python = ">=3.14"
dependencies = [
    "cryptography>=45.0",
    "keyring>=25.6",
    "pyjwt>=2.10",
    "platformdirs>=4.3",
    "numpy>=2.3.3",
    "uvloop>=0.22.1",
    "winloop>=0.4.0",
    "pyroh",
    "compass",
    "hypixel-py>=0.4.2",
]

[project.scripts]
proxhy = "proxhy.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["proxhy", "core", "plugins", "auth", "protocol"]

[tool.setuptools.package-data]
"proxhy" = ["assets/*"]

[tool.uv.sources]
pyroh = { git = "https://github.com/kbidlack/pyroh" }
compass = { git = "https://github.com/kbidlack/compass.git", subdirectory = "client-python" }
