[project]
name = "proxhy"
version = "0.1.0"
description = "Proxy for Hypixel"
authors = [
    { name = "Kavi Bidlack", email = "ksbidlack@gmail.com" }
]
dependencies = [
    "aiohttp>=3.9.3",
    "hypixel.py[speed]>=0.4.2",
    "appdirs>=1.4.4",
    "cryptography>=42.0.5",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/proxhy"]
