[project]
name = "proxhy"
version = "1.0.0"
description = "A Hypixel Proxy"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.10.10",
    "appdirs>=1.4.4",
    "cryptography>=43.0.3",
    "hypixel-py[speed]>=0.4.2",
]
